repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3
    hooks:
    -   id: lintr
        args: [--warn_only, --key=value]
    -   id: style-files
        args: [--scope=spaces, --reindention=specify_reindention('#')]

