---
title: "Data Modeling"
author: "Farhan Reynaldo"
date: "2024-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("scripts/03_data-modeling.Rmd")
```


```{r}
library(rstanarm)
library(tidybayes)
library(tidyverse)
library(here)
library(brms)

source(here::here("src/helpers.R"))
source(here::here("src/theme.R"))
source(here::here("src/load_data.R"))

map_data <- usmap::us_map(regions = "states")
poststrat_data <- read_csv(here("data/census-pums-pop-2016.csv")) %>%
  mutate(pop2008 = wtpop)

# options(mc.cores = parallelly::availableCores())
```

```{r}
prepare_data <- function(year) {
  states_data <- process_states_data(states_election_data, states_pop_income_data, year)
  election_processed <- process_election_data(election_all, year)
  covariates <- c("stt", "eth", "inc", "age", "educ", "metro")
  
  data_matrix <- expand.grid(
    stt = factor(1:length(stt.label)),
    eth = factor(1:length(eth.label)),
    inc = factor(1:length(inc.label)),
    age = factor(1:length(age.label)),
    educ = factor(1:length(educ.label)),
    metro = factor(1:length(metro.label))
  ) %>%
    mutate(
      grp = apply(., 1, paste, collapse = "_"),
      ix = row_number()
    ) %>%
    left_join(states_data, by = c("stt" = "stt")) %>%
    mutate(
      reg = factor(reg.lkup[as.numeric(stt)]),
      z_inc = arm::rescale(as.numeric(inc))
    )
  
  election_subset <- election_processed %>%
    mutate(
      # Vote for Republican
      vote = ifelse(vote == "Republican", 1, 0),
      grp = apply(.[, covariates], 1, paste, collapse = "_"),
      ones = 1
    )
  
  data_matrix <- calc_and_add_weighted_results(data_matrix, election_subset)
  return(data_matrix)
}

fit_model <- function(data_matrix, formula_level = 1, run = FALSE) {
  if (run == FALSE) {
    return(NULL)
  }
  year <- unique(data_matrix$year)
  if(formula_level == 1) {
    formula <- "cbind(yes, no) ~ z_incstt + z_trnprv + reg + stt + eth + educ + age + metro + inc"
  } else if (formula_level == 2) {
    formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv + (1 | reg) + (1 | stt) + (1 | eth)  + (1 | educ) + (1 | age) + (1 | metro) + (1 | inc)"
  } else if (formula_level == 3) {
    formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv + (1 + z_inc | reg) + (1 + z_inc | stt) + (1 + z_inc | eth)  + (1 + z_inc | educ) + (1 + z_inc | age) + (1 + z_inc | metro) + (1 | inc)"
  } else if (formula_level == 4) {
    formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv +
    (1 + z_inc | reg) + (1 + z_inc | stt) + (1 + z_inc | eth)  + (1 + z_inc | educ) + (1 + z_inc | age) + (1 + z_inc | metro) + (1 | inc) + (1 | reg : eth) + (1 | reg : inc) + (1 | reg : age) + (1 | reg : metro) + (1 | stt : eth) + (1 | stt : inc) + (1 | stt : age) + (1 | stt : metro) + (1 | eth : inc) + (1 | eth : age) + (1 | eth : metro) + (1 | inc : age) + (1 | inc : metro) + (1 | educ : age) + (1 | educ : stt) + (1 | educ : inc) + (1 | educ : eth) + (1 | educ : reg) + (1 | educ : metro) + (1 | educ : metro : inc)"
  } else {
    stop("Invalid formula level")
  }
  
  if(formula_level == 1) {
  model <- stan_glm(formula, data = data_matrix, family = binomial(link = "logit"),
                    iter = 1000, prior = normal(0, 1, autoscale = TRUE),
                    prior_intercept = normal(0, 1, autoscale = TRUE))
  } else {
    model <- stan_glmer(formula, data = data_matrix, family = binomial(link = "logit"),
                      iter = 1000, prior = normal(0, 1, autoscale = TRUE),
                      prior_covariance = decov(scale = 0.50),
                      adapt_delta = 0.99, 
                      seed = 10027)
  }
  model_filename <- glue::glue("model_matrix_complete-{year}-formula_level_{formula_level}.rds")
  model_matrix <- list(model = model, data_matrix = data_matrix, name = model_filename)
  saveRDS(model_matrix, model_filename)
  return(model_matrix)
}
```

```{r}
years <- c(2008, 2012, 2016, 2020)
data_matrices <- lapply(years, prepare_data)
saveRDS(data_matrices, here("data/data_matrices.rds"))

models <- vector("list", length(data_matrices))
for (i in seq_along(years)) {
  models[[i]] <- fit_model(data_matrices[[i]], formula_level = 4, run = TRUE)
}
```

```{r}
model_matrix_filenames <- list.files(
    path = ".", 
    pattern = "model_matrix_complete-\\d{4}-formula_level_\\w+\\.rds",
    full.names = TRUE
  )

for(filename in model_matrix_filenames) {
  output_filename <- stringr::str_replace(filename, "model_matrix", "pred")
  model_matrix <- readRDS(filename)
  pred <- posterior_epred(model_matrix$model, newdata = model_matrix$data_matrix)
  saveRDS(pred, output_filename)
}
```
