---
title: "Data visualization"
author: "Farhan Reynaldo"
date: "2024-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("scripts/data-modeling-2.Rmd")

ssh_private_key_file <- "~/.ssh/id_rsa"
```


```{r}
library(rstanarm)
library(tidybayes)
library(tidyverse)
library(here)
library(analogsea)
library(future)
library(listenv)

source(here::here("src/election.R"))
source(here::here("src/helpers.R"))
source(here::here("src/theme.R"))
source(here::here("src/load_data.R"))

map_data <- usmap::us_map(regions = "states")
poststrat_data <- read_csv(here("data/census-pums-pop-2016.csv")) %>%
  mutate(pop2008 = wtpop)

# options(mc.cores = parallelly::availableCores())
```


```{r}
year <- 2016
run <- FALSE

states_data <- process_states_data(states_election_data, states_pop_income_data, year)
election_processed <- process_election_data(election_all, year)
covariates <- c("stt", "eth", "inc", "age", "educ", "metro")

data_matrix <- expand.grid(
  stt = factor(1:length(stt.label)),
  eth = factor(1:length(eth.label)),
  inc = factor(1:length(inc.label)),
  age = factor(1:length(age.label)),
  educ = factor(1:length(educ.label)),
  metro = factor(1:length(metro.label))
) %>%
  mutate(
    grp = apply(., 1, paste, collapse = "_"),
    ix = row_number()
  ) %>%
  left_join(states_data, by = c("stt" = "stt")) %>%
  mutate(
    reg = factor(reg.lkup[as.numeric(stt)]),
    z_inc = arm::rescale(as.numeric(inc))
  )

election_subset <- election_processed %>%
  mutate(
    # Vote for Republican
    vote = ifelse(vote == "Republican", 1, 0),
    grp = apply(.[, covariates], 1, paste, collapse = "_"),
    ones = 1
  )

# Calculate and add weighted results
data_matrix <- calc_and_add_weighted_results(data_matrix, election_subset)

# Build and fit model
reg_formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv +
(1 + z_inc | reg) + (1 + z_inc | stt) + (1 + z_inc | eth)  + (1 + z_inc | educ) + (1 + z_inc | age) + (1 + z_inc | metro) + (1 | inc) + (1 | reg : eth) + (1 | reg : inc) + (1 | reg : age) + (1 | reg : metro) + (1 | stt : eth) + (1 | stt : inc) + (1 | stt : age) + (1 | stt : metro) + (1 | eth : inc) + (1 | eth : age) + (1 | eth : metro) + (1 | inc : age) + (1 | inc : metro) + (1 | educ : age) + (1 | educ : stt) + (1 | educ : inc) + (1 | educ : eth) + (1 | educ : reg) + (1 | educ : metro)"


if (run == TRUE) {
  model <- stan_glmer(reg_formula,
    data = data_matrix,
    family = binomial(link = "logit"), iter = 500
  )

  pred <- posterior_epred(model, newdata = data_matrix)
  model_matrix <- list(model = model, data_matrix = data_matrix, pred = pred)
  saveRDS(model_matrix, here("data/model_matrix_complete_2020.rds"))
}
```


```{r}
# fit_model <- function(year, formula_level = 1, run = FALSE) {
#   if (run == FALSE) {
#     return(NULL)
#   }
#   states_data <- process_states_data(states_election_data, states_pop_income_data, year)
#   election_processed <- process_election_data(election_all, year)
#   covariates <- c("stt", "eth", "inc", "age", "educ", "metro")
#   
#   data_matrix <- expand.grid(
#     stt = factor(1:length(stt.label)),
#     eth = factor(1:length(eth.label)),
#     inc = factor(1:length(inc.label)),
#     age = factor(1:length(age.label)),
#     educ = factor(1:length(educ.label)),
#     metro = factor(1:length(metro.label))
#   ) %>%
#     mutate(
#       grp = apply(., 1, paste, collapse = "_"),
#       ix = row_number()
#     ) %>%
#     left_join(states_data, by = c("stt" = "stt")) %>%
#     mutate(
#       reg = factor(reg.lkup[as.numeric(stt)]),
#       z_inc = arm::rescale(as.numeric(inc))
#     )
#   
#   election_subset <- election_processed %>%
#     mutate(
#       # Vote for Republican
#       vote = ifelse(vote == "Republican", 1, 0),
#       grp = apply(.[, covariates], 1, paste, collapse = "_"),
#       ones = 1
#     )
#   
#   data_matrix <- calc_and_add_weighted_results(data_matrix, election_subset)
#   
#   if(formula_level == 1) {
#     formula <- "cbind(yes, no) ~ z_incstt + z_trnprv + reg + stt + eth + educ + age + metro + inc"
#   } else if (formula_level == 2) {
#     formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv + (1 | reg) + (1 | stt) + (1 | eth)  + (1 | educ) + (1 | age) + (1 | metro) + (1 | inc)"
#   } else if (formula_level == 3) {
#     formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv + (1 + z_inc | reg) + (1 + z_inc | stt) + (1 + z_inc | eth)  + (1 + z_inc | educ) + (1 + z_inc | age) + (1 + z_inc | metro) + (1 | inc)"
#   } else if (formula_level == 4) {
#     formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv +
#     (1 + z_inc | reg) + (1 + z_inc | stt) + (1 + z_inc | eth)  + (1 + z_inc | educ) + (1 + z_inc | age) + (1 + z_inc | metro) + (1 | inc) + (1 | reg : eth) + (1 | reg : inc) + (1 | reg : age) + (1 | reg : metro) + (1 | stt : eth) + (1 | stt : inc) + (1 | stt : age) + (1 | stt : metro) + (1 | eth : inc) + (1 | eth : age) + (1 | eth : metro) + (1 | inc : age) + (1 | inc : metro) + (1 | educ : age) + (1 | educ : stt) + (1 | educ : inc) + (1 | educ : eth) + (1 | educ : reg) + (1 | educ : metro)"
#   } else {
#     stop("Invalid formula level")
#   }
#   
#   if(formula_level == 1) {
#   model <- stan_glm(formula, data = data_matrix, family = binomial(link = "logit"),
#                       iter = 1000)
#   } else {
#     model <- stan_glmer(formula, data = data_matrix, family = binomial(link = "logit"),
#                       iter = 1000)
#   }
#   pred <- posterior_epred(model, newdata = data_matrix)
#   model_loo <- loo(model)
#   model_filename <- glue::glue("model_matrix_complete-{year}-formula_level_{formula_level}.rds")
#   model_matrix <- list(model = model, data_matrix = data_matrix, pred = pred, 
#                        loo = model_loo, name = model_filename)
#   # saveRDS(model_matrix, model_matrix_path)
# }
```


```{r}
# droplet1 <- docklet_create(region = "nyc2", size = "s-4vcpu-8gb")
# droplet2 <- docklet_create(region = "nyc2", size = "s-4vcpu-8gb")
# droplet3 <- docklet_create(region = "nyc2", size = "s-4vcpu-8gb")
# 
# droplet(droplet1$id) %>%
#   docklet_pull("asachet/rocker-stan")
# 
# droplet(droplet2$id) %>%
#   docklet_pull("asachet/rocker-stan")
# 
# droplet(droplet3$id) %>%
#   docklet_pull("asachet/rocker-stan")
# 
# ip1 <- droplet(droplet1$id)$networks$v4[[1]]$ip_address
# ip2 <- droplet(droplet2$id)$networks$v4[[1]]$ip_address
# ip3 <- droplet(droplet3$id)$networks$v4[[1]]$ip_address
# ips <- c(ip1, ip2, ip3)
# 
# rscript <- c("sudo", "docker", "run", "--net=host", 
#              "asachet/rocker-stan", "Rscript")
# 
# # Connect and create a cluster
# cl <- makeClusterPSOCK(
#   ips,
#   
#   # User name; DO droplets use root by default
#   user = "root",
#   
#   # Use private SSH key registered with DO
#   rshopts = c(
#     "-o", "StrictHostKeyChecking=no",
#     "-o", "IdentitiesOnly=yes",
#     "-i", ssh_private_key_file
#   ),
#   
#   rscript = rscript,
#   
#   # Things to run each time the remote instance starts
#   rscript_args = c(
#     # Set up .libPaths() for the root user and install future/purrr/furrr packages
#     "-e", shQuote("local({p <- Sys.getenv('R_LIBS_USER'); dir.create(p, recursive = TRUE, showWarnings = FALSE); .libPaths(p)})"),
#     # "-e", shQuote("if (!requireNamespace('purrr', quietly = TRUE)) install.packages('purrr')"),
#     # "-e", shQuote("if (!requireNamespace('furrr', quietly = TRUE)) install.packages('furrr')"),
#     # Make sure the remote computer uses all CPU cores with Stan
#     "-e", shQuote("options(mc.cores = parallel::detectCores())")
#   ),
#   dryrun = FALSE
# )
# 
# # Create the future plan
# plan(list(
#   tweak(cluster, workers = cl), 
#   multisession
# ))
```

```{r}
# remote_name %<-% {
#   Sys.info()[["nodename"]]
# }; remote_name
```

```{r}
prepare_data <- function(year) {
  states_data <- process_states_data(states_election_data, states_pop_income_data, year)
  election_processed <- process_election_data(election_all, year)
  covariates <- c("stt", "eth", "inc", "age", "educ", "metro")
  
  data_matrix <- expand.grid(
    stt = factor(1:length(stt.label)),
    eth = factor(1:length(eth.label)),
    inc = factor(1:length(inc.label)),
    age = factor(1:length(age.label)),
    educ = factor(1:length(educ.label)),
    metro = factor(1:length(metro.label))
  ) %>%
    mutate(
      grp = apply(., 1, paste, collapse = "_"),
      ix = row_number()
    ) %>%
    left_join(states_data, by = c("stt" = "stt")) %>%
    mutate(
      reg = factor(reg.lkup[as.numeric(stt)]),
      z_inc = arm::rescale(as.numeric(inc))
    )
  
  election_subset <- election_processed %>%
    mutate(
      # Vote for Republican
      vote = ifelse(vote == "Republican", 1, 0),
      grp = apply(.[, covariates], 1, paste, collapse = "_"),
      ones = 1
    )
  
  data_matrix <- calc_and_add_weighted_results(data_matrix, election_subset)
  return(data_matrix)
}

`fit_model <- function(data_matrix, formula_level = 1, run = FALSE) {
  if (run == FALSE) {
    return(NULL)
  }
  year <- unique(data_matrix$year)
  if(formula_level == 1) {
    formula <- "cbind(yes, no) ~ z_incstt + z_trnprv + reg + stt + eth + educ + age + metro + inc"
  } else if (formula_level == 2) {
    formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv + (1 | reg) + (1 | stt) + (1 | eth)  + (1 | educ) + (1 | age) + (1 | metro) + (1 | inc)"
  } else if (formula_level == 3) {
    formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv + (1 + z_inc | reg) + (1 + z_inc | stt) + (1 + z_inc | eth)  + (1 + z_inc | educ) + (1 + z_inc | age) + (1 + z_inc | metro) + (1 | inc)"
  } else if (formula_level == 4) {
    formula <- "cbind(yes, no) ~ z_inc*z_incstt + z_inc*z_trnprv +
    (1 + z_inc | reg) + (1 + z_inc | stt) + (1 + z_inc | eth)  + (1 + z_inc | educ) + (1 + z_inc | age) + (1 + z_inc | metro) + (1 | inc) + (1 | reg : eth) + (1 | reg : inc) + (1 | reg : age) + (1 | reg : metro) + (1 | stt : eth) + (1 | stt : inc) + (1 | stt : age) + (1 | stt : metro) + (1 | eth : inc) + (1 | eth : age) + (1 | eth : metro) + (1 | inc : age) + (1 | inc : metro) + (1 | educ : age) + (1 | educ : stt) + (1 | educ : inc) + (1 | educ : eth) + (1 | educ : reg) + (1 | educ : metro) + (1 | educ : metro : inc)"
  } else {
    stop("Invalid formula level")
  }
  
  if(formula_level == 1) {
  model <- stan_glm(formula, data = data_matrix, family = binomial(link = "logit"),
                    iter = 500, prior = normal(0, 1, autoscale = TRUE),
                    prior_intercept = normal(0, 1, autoscale = TRUE))
  } else {
    model <- stan_glmer(formula, data = data_matrix, family = binomial(link = "logit"),
                      iter = 500, prior = normal(0, 1, autoscale = TRUE),
                      prior_covariance = decov(scale = 0.50),
                      adapt_delta = 0.99, 
                      seed = 10027)
  }
  # pred <- posterior_epred(model, newdata = data_matrix)
  model_filename <- glue::glue("model_matrix_complete-{year}-formula_level_{formula_level}.rds")
  model_matrix <- list(model = model, data_matrix = data_matrix, name = model_filename)
  saveRDS(model_matrix, model_filename)
  return(model_matrix)
}`
```

```{r}
years <- c(2012, 2016, 2020)
data_matrices <- lapply(years, prepare_data)
# data_matrices %>% saveRDS(here("data/data_matrices.rds"))

models <- vector("list", length(data_matrices))
for (i in seq_along(years)) {
  models[[i]] <- fit_model(data_matrices[[i]], formula_level = 4, run = TRUE)
}
```

```{r}
library(analogsea)

# Create volume and droplet (your existing code)
vol1 <- volume_create('test', 1)
droplet1 <- docklet_create(region = "nyc2", size = "s-1vcpu-1gb", volume = vol1)
docklet_ps(droplet1)

droplet_delete(droplet1)
```


```{r, fig.width = 10, fig.height = 10}
model_matrix <- readRDS(here("data/model_matrix_complete_2016.rds"))
model <- model_matrix$model
data_matrix <- model_matrix$data_matrix

# Poststratification
result <- poststrat_data %>%
  mutate(grp = apply(.[, c("stt", "eth", "inc", "age", "educ", "metro")], 1, paste, collapse = "_")) %>%
  group_by(grp) %>%
  summarise(
    pop2008 = sum(wtpop, na.rm = TRUE)
  ) %>%
  right_join(data_matrix, by = "grp") %>%
  arrange(ix)

# Plot results
plot_result <- result %>%
  mutate(pred = colMeans(model_matrix$pred)) %>%
  group_by(stt, educ) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1]),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
    se_white = sqrt((pred_white * (1 - pred_white)) / sum(n[eth == 1]))
  ) %>%
  ungroup() %>%
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  dplyr::filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(states_data %>% dplyr::filter(year == year) %>% dplyr::select(state_abbr, rep_votes), by = c("state_abbr" = "state_abbr")) %>%
  mutate(state_name = fct_reorder(state_name, rep_votes, .desc = TRUE)) %>%
  arrange(-rep_votes) %>%
  left_join(election_subset, by = c("stt", "educ"))

title <- "2020 Election: Republican vote share for each education level across states\namong all voters (grey) and white voters (orange)"

plot_result %>%
  ggplot(aes(group = 1)) +
  geom_line(aes(x = educ, y = pred_all, color = "grey")) +
  geom_line(aes(x = educ, y = pred_white, color = "orange")) +
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) +
  scale_color_identity() +
  labs(title = title, x = "", y = "") +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 6),
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "none"
  )
```


```{r, fig.width = 10, fig.height = 10}
# Plot results
plot_result <- result %>%
  mutate(pred = colMeans(model_matrix$pred)) %>%
  group_by(stt, inc) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1]),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
    se_white = sqrt((pred_white * (1 - pred_white)) / sum(n[eth == 1]))
  ) %>%
  ungroup() %>%
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  dplyr::filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(states_data %>% dplyr::filter(year == year) %>% dplyr::select(state_abbr, rep_votes), by = c("state_abbr" = "state_abbr")) %>%
  mutate(state_name = fct_reorder(state_name, rep_votes, .desc = TRUE)) %>%
  arrange(-rep_votes) %>%
  left_join(election_subset, by = c("stt", "inc"))

title <- "2020 Election: Republican vote share for each education level across states\namong all voters (grey) and white voters (orange)"

plot_result %>%
  ggplot(aes(group = 1)) +
  geom_line(aes(x = inc, y = pred_all, color = "grey")) +
  geom_line(aes(x = inc, y = pred_white, color = "orange")) +
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) +
  scale_color_identity() +
  labs(title = title, x = "", y = "") +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 6),
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "none"
  )
```


```{r}
result %>%
  mutate(pred = colMeans(model_matrix$pred)) %>%
  group_by(inc, educ) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
  ) %>%
  ungroup() %>%
  ggplot(aes(inc, pred_all, group = educ, color = educ)) +
  geom_line()
```


```{r}
result %>%
  mutate(pred = colMeans(model_matrix$pred)) %>%
  group_by(inc, educ) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
  ) %>%
  ungroup() %>%
  ggplot(aes(educ, pred_all, group = inc, color = inc)) +
  geom_line()
```

```{r, fig.width = 10, fig.height = 10}
result %>%
  mutate(pred = colMeans(model_matrix$pred)) %>%
  mutate(educ = if_else(educ %in% c(1, 2, 3), "No college", "College")) %>%
  group_by(stt, educ, inc) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n))
  ) %>%
  ungroup() %>%
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  dplyr::filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(states_data %>% dplyr::filter(year == year) %>% dplyr::select(state_abbr, rep_votes), by = c("state_abbr" = "state_abbr")) %>%
  mutate(state_name = fct_reorder(state_name, rep_votes, .desc = TRUE)) %>%
  arrange(-rep_votes) %>%
  ggplot(aes(educ, pred_all, group = inc, color = inc)) +
  geom_line() +
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  # scale_color_manual(values = c("No college" = "grey", "College" = "orange")) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 6),
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10)
  )
```
