---
title: "Data exploration"
author: "Farhan Reynaldo"
date: "2024-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("scripts/data-exploration-2.Rmd")
```

## Load library and data

```{r}
library(tidyverse)
library(arrow)
library(srvyr)
library(here)

source(here("src/election.R"))
source(here("src/theme.R"))

election_all <- read_feather(here("data/CCES Cumulative/cumulative_2006-2023.feather"))

poststrat_data <- read_csv(here("data/census-pums-pop.csv")) %>% 
  dplyr::select(!starts_with("pop")) %>% 
  mutate(across(starts_with("wtpop"), ~replace_na(.x, 0))) %>% 
  pivot_longer(cols = starts_with("wtpop"), names_to = "year", values_to = "wtpop", 
               names_prefix = "wtpop")
```

```{r}
# Define constants
reg.lkup <- c(3, 4, 4, 3, 4, 4, 1, 1, 5, 3, 3, 4, 4, 2, 2, 2, 2, 3, 3, 1, 1, 1, 2, 2, 3, 2, 4, 2, 4, 1, 1, 4, 1, 3, 2, 2, 3, 4, 1, 1, 3, 2, 3, 3, 4, 1, 3, 4, 1, 2, 4)
stt.label <- c(state.name[1:8], "DC", state.name[9:50])
stt.abb.label <- c(state.abb[1:8], "DC", state.abb[9:50])
eth.label <- c("White", "Black", "Hispanic", "Other")
inc.label <- c("$0-20k", "$20-40k", "$40-75k", "$75-150k", "$150k+")
age.label <- c("18-29", "30-44", "45-64", "65+")
sex.label <- c("Male", "Female")
educ.label <- c("< HS", "HS", "Some College", "College", "Post-Grad")
metro.label <- c("Rural", "Suburban", "Urban")

# Create state dictionary
stt_dict <- data.frame(
  state_name = stt.label, state_abbr = stt.abb.label, stt = factor(1:51)
)

# COLORS <- c("#fdbb84", "#fc8d59", "#e34a33", "#b30000")
COLORS <- c("#fdbb84", "#fc8d59", "#e34a33")
COL_NAMES <- c("eth", "inc", "age", "educ", "metro")
```

## Elections

```{r}
years <- seq(2012, 2020, 4)
elections <- purrr::map(years, ~process_election_data(election_all, year = .x)) %>% 
  purrr::list_rbind() %>% 
  mutate(across(is.labelled, ~as_factor(.)))
```

## Function 

```{r}
get_label <- function(col_name) {
  label <- switch(col_name,
    eth = eth.label,
    inc = inc.label,
    age = age.label,
    educ = educ.label,
    metro = metro.label,
    stt = stt.label
  )
  return(label)
}

relevel_label <- function(col_name) {
  col_name <- deparse(substitute(col_name))
  get_label(col_name)
}

map_label <- function(col) {
  col_name <- deparse(substitute(col))
  label <- get_label(col_name)
  label_mapper <- setNames(label, 1:length(label))
  result <- unname(label_mapper[as.character(col)])
  fct_relevel(result, label)
}

create_survey_means <- function(data, ..., year = NULL) {
  group_vars <- enquos(...)
  
  survey_data <- data %>% 
    as_survey(weights = weight)

  if (!is.null(year)) {
    survey_data <- survey_data %>% 
      filter(year == !!year)
  }

  survey_data %>% 
    group_by(year, !!!group_vars) %>% 
    summarise(vote = survey_mean(vote == "Republican"), .groups = "drop") %>% 
    mutate(across(is.factor, map_label, .names = "{.col}_str"),
           year = factor(year, ordered = TRUE))
}
```

## Distribution

```{r}


plot_variable <- function(col_name) {
  elections %>%
    mutate(col = map_label(!!ensym(col_name)),
           year = factor(year, ordered = TRUE)) %>%
    group_by(year, col) %>%
    summarise(count = n(), .groups = "drop") %>% 
    group_by(year) %>%
    mutate(prop = count/sum(count)) %>%
    ungroup() %>%
    ggplot(aes(x = prop, y = col, fill = year)) +
    geom_col(position = "dodge") +
    theme_benedict() +
    scale_fill_manual(values = COLORS) +
    scale_x_continuous(labels = scales::label_percent()) +
    labs(title = col_name, x = "", y = "") +
    theme(axis.text.y = element_text(size = 10))
}

purrr::map(COL_NAMES, plot_variable)
```


```{r}
plot_dist_pop <- function(col_name) {
  poststrat_data %>% 
    mutate(col = map_label(!!ensym(col_name)),
           year = factor(year, ordered = TRUE)) %>%
    group_by(year, col) %>% 
    summarise(wtpop = sum(wtpop), .groups = "drop") %>%
    group_by(year) %>%
    mutate(prop = wtpop/sum(wtpop)) %>%
    ungroup() %>%
    ggplot(aes(x = prop, y = col, fill = year)) +
    geom_col(position = "dodge") +
    theme_benedict() +
    scale_fill_manual(values = c("#fdbb84", "#fc8d59", "#e34a33", "#b30000")) +
    scale_x_continuous(labels = scales::label_percent()) +
    labs(title = col_name, x = "", y = "") +
    theme(axis.text.y = element_text(size = 10))
}

purrr::map(COL_NAMES, plot_dist_pop)
```


## state-income

```{r, fig.width=12, fig.height=12}
elections %>%
  create_survey_means(stt, inc, year = 2012) %>% 
  drop_na(inc_str) %>% 
  ggplot(aes(x = inc_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~stt_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic()
```

## age-state

```{r, fig.width=12, fig.height=12}
elections %>%
  create_survey_means(stt, age, year = 2012) %>% 
  ggplot(aes(x = age_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~stt_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic()
```

## income-educ

```{r, fig.width=9, fig.height=6}
elections %>%
  create_survey_means(inc, educ, year = 2016) %>%
  ggplot(aes(x = educ_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~inc_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "Education level", y = "Republican Vote Share (%)", 
       title = "Republican Two-Party Vote Share by Income and Education Level") +
  theme_classic() 
```


```{r, fig.width=9, fig.height=6}
elections %>%
  create_survey_means(inc, educ) %>% 
  ggplot(aes(x = educ_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~inc_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "Education level", y = "Republican Vote Share (%)", 
       title = "Republican Two-Party Vote Share by Income and Education Level") +
  theme_classic() 
```

```{r, fig.width=9, fig.height=6}
elections %>%
  create_survey_means(inc, educ) %>% 
  drop_na(inc_str, educ_str) %>% 
  ggplot(aes(x = inc_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~educ_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "Education level", y = "Republican Vote Share (%)", 
       title = "Republican Two-Party Vote Share by Income and Education Level") +
  theme_classic() 
```

## metro-educ

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(metro, educ, year = 2016) %>%
  ggplot(aes(x = educ_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~metro_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "Education level", y = "Republican Vote Share (%)", 
       title = "Republican Two-Party Vote Share by Metro Status and Education Level") +
  theme_classic() 
```

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(metro, educ) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = educ_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~metro_str, ncol = 2) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "Education level", y = "Republican Vote Share (%)", 
       title = "Republican Two-Party Vote Share by Metro Status and Education Level") +
  theme_classic() 
```

## eth-educ

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(eth, educ, year = 2016) %>% 
  ggplot(aes(x = educ_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~eth_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "Education level", y = "Republican Vote Share (%)", 
       title = "Republican Two-Party Vote Share by Ethnicity and Education Level") +
  theme_classic() 
```

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(eth, educ) %>% 
  ggplot(aes(x = educ_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~eth_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

## age-educ

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(age, educ, year = 2016) %>% 
  ggplot(aes(x = educ_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~age_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(age, educ) %>% 
  ggplot(aes(x = educ_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~age_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

## state-educ

```{r, fig.width=12, fig.height=12}
elections %>%
  create_survey_means(stt, educ, year = 2016) %>% 
  ggplot(aes(x = educ_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~stt_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

```{r, fig.width=12, fig.height=12}
elections %>%
  create_survey_means(stt, educ) %>% 
  ggplot(aes(x = educ_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~stt_str, ncol = 7) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

## income-metro

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(inc, metro, year = 2016) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~inc_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(inc, metro) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~inc_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

## age-metro

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(age, metro, year = 2016) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~age_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(age, metro) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~age_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

## eth-metro

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(eth, metro, year = 2016) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~eth_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

```{r, fig.width=8, fig.height=5}
elections %>%
  create_survey_means(eth, metro) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~eth_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

## state-metro

```{r, fig.width=12, fig.height=12}
elections %>%
  create_survey_means(stt, metro, year = 2016) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se)) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~stt_str) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```

```{r, fig.width=12, fig.height=12}
elections %>%
  create_survey_means(stt, metro) %>% 
  filter(metro != -1) %>% 
  ggplot(aes(x = metro_str, y = vote, color = year, group = year)) +
  geom_pointrange(aes(ymin = vote - vote_se, ymax = vote + vote_se), size = 0.2, 
                  alpha = 0.7) + 
  geom_line() + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~stt_str) +
  scale_color_manual(values = COLORS) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.25)) + 
  coord_cartesian(ylim = c(0, 1)) +
  theme_classic() 
```
