---
title: "Data exploration"
author: "Farhan Reynaldo"
date: "2024-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("scripts/data-replication.Rmd")
```

```{r}
library(tidyverse)
library(haven)
library(here)
library(rstanarm)
library(ipumsr)
library(ggtext)

options(mc.cores = parallel::detectCores())
```

```{r}
# load("../../election_stan_analysis/Stan MRP R Code/stan-MRP-20120715.RData")
src("../src/helpers.R")

reg.lkup <- c(3,4,4,3,4,4,1,1,5,3,3,4,4,2,2,2,2,3,3,1,1,1,2,2,3,2,4,2,4,1,1,4,1,3,2,2,3,4,1,1,3,2,3,3,4,1,3,4,1,2,4)

# Define constants
reg.lkup <- c(3, 4, 4, 3, 4, 4, 1, 1, 5, 3, 3, 4, 4, 2, 2, 2, 2, 3, 3, 1, 1, 1, 2, 2, 3, 2, 4, 2, 4, 1, 1, 4, 1, 3, 2, 2, 3, 4, 1, 1, 3, 2, 3, 3, 4, 1, 3, 4, 1, 2, 4)
stt.label <- c(state.name[1:8], "DC", state.name[9:50])
stt.abb.label <- c(state.abb[1:8], "DC", state.abb[9:50])
eth.label <- c("White", "Black", "Hispanic", "Other")
inc.label <- c("$0-20k", "$20-40k", "$40-75k", "$75-150k", "$150k+")
age.label <- c("18-29", "30-44", "45-64", "65+")
sex.label <- c("Male", "Female")
educ.label <- c("< HS", "HS", "Some College", "College", "Post-Grad")

# Create state dictionary
stt_dict <- data.frame(
  state_name = stt.label, state_abbr = stt.abb.label, stt = factor(1:51)
)

### state-level data
dat.stt <- read.table("../data/state-stats.dat", header=T, sep="\t")
dat.stt$z.inc2000 <- rescale(dat.stt$inc2000)
dat.stt$z.inc2004 <- rescale(dat.stt$inc2004)
dat.stt$z.inc2007 <- rescale(dat.stt$inc2007)
dat.stt$z.rep1996 <- rescale(dat.stt$rep1996)
dat.stt$z.rep2000 <- rescale(dat.stt$rep2000)
dat.stt$z.rep2004 <- rescale(dat.stt$rep2004)
dat.stt$z.rep2008 <- rescale(dat.stt$rep2008)
dat.stt$z.trn1996 <- rescale(dat.stt$vote1996/dat.stt$pop1996)
dat.stt$z.trn2000 <- rescale(dat.stt$vote2000/dat.stt$pop2000)
dat.stt$z.trn2004 <- rescale(dat.stt$vote2004/dat.stt$pop2004)
dat.stt$z.trn2008 <- rescale(dat.stt$vote2008/dat.stt$pop2007)
dat.stt$stt <- 1:nrow(dat.stt)

### annenberg / pew data for modeling vote choice
dat.vot <- read.table("../data/votechoice2000-04-08.dat", header=T, sep="\t")
dat.vot$weight[is.na(dat.vot$weight)] <- 1
ok <- apply(is.na(dat.vot[1:8]), 1, sum)==0 & 
  (dat.vot$cit==1 | is.na(dat.vot$cit)) & 
  (dat.vot$regist=="registered" | is.na(dat.vot$regist))
dat.vot <- dat.vot[ok,]
dat.vot$reg <- reg.lkup[dat.vot$stt]
dat.vot$year <- car::recode(dat.vot$file, "'2000-ann'=2000; '2004-ann'=2004; '2008-pew'=2008")
dat.vot <- dat.vot[dat.vot$year != 2000,]

### census data from PUMS for population cell sizes
dat.pop <- read.table("../data/census-pums-pop-2000-04-08.dat", header=T, sep="\t")

n.stt <- length(stt.label)
n.eth <- length(eth.label)
n.inc <- length(inc.label)
n.age <- length(age.label)

data_matrix <- as.data.frame(expand.grid(1:n.stt, 1:n.eth, 1:n.inc, 1:n.age))
colnames(data_matrix) <- c("stt", "eth", "inc", "age")
data_matrix$age <- factor(data_matrix$age)
data_matrix$eth <- factor(data_matrix$eth)
data_matrix$inc <- factor(data_matrix$inc)
data_matrix$stt <- factor(data_matrix$stt)

data_matrix$grp <- apply(data_matrix, 1, paste, collapse="_")
data_matrix$ix <- 1:nrow(data_matrix)

### Fit 2008 election, with data prev states data (2004)
data_matrix <- mutate(data_matrix,
                      reg = factor(reg.lkup[stt]),
                      z_inc = rescale(inc),
                      z_incstt = dat.stt$z.inc2007[stt],
                      z_trnprv = dat.stt$z.trn2004[stt],
                      z_repprv = dat.stt$z.rep2004[stt])
```

## Replicate stan result

```{r}
i.year <- 2
years <- c(2004, 2008)
tmp <- dat.vot[dat.vot$year==years[i.year],]
tmp$grp <- apply(tmp[, c("stt", "eth", "inc", "age")], 1, paste, collapse = "_")
tmp$ones <- 1
tmp <- rename(tmp,vote = rvote)
data_matrix <- calc_and_add_weighted_results(data_matrix, tmp)
reg_formula <- as.formula(build_formula(level = 3))

start.time <- Sys.time()
mod <- stan_glmer(reg_formula,
  data = data_matrix, family = binomial(link = "logit"),
  iter = 500
)
end.time <- Sys.time()
time.taken <- end.time - start.time

pred <- posterior_epred(mod, newdata = data_matrix)

dat.pop$grp <- apply(dat.pop[, c("stt", "eth", "inc", "age")], 1, paste, collapse="_")
data_pop_info <- summarize(group_by(dat.pop, grp),
                           pop2004=sum(wtd2004),
                           pop2008=sum(wtd2008))
# data_pop_info$grp <- rownames(data_pop_info)
data_matrix <- merge(x=data_matrix, y=data_pop_info, by="grp", all.x=T)
data_matrix <- data_matrix[order(data_matrix$ix),]
data_matrix$pred = colMeans(pred)

## add up and alter based on actual turnout and vote estimates
data_matrix$vote2008 <- data_matrix$vote2004 <- data_matrix$turn2008 <- data_matrix$turn2004 <- NA
for (i in 1:n.stt) {
  cat(paste(i, "of", n.stt, "\n"))
  ok <- data_matrix$stt==i
  data_matrix$vote2008[ok] <- weighted_correction(data_matrix$pred[ok], data_matrix$pop2008[ok]/sum(data_matrix$pop2008[ok]), dat.stt[as.character(i), "rep2008"])$corrected
}

model_matrix_ori <- list(model = mod, data_matrix = data_matrix, pred = pred)
# saveRDS(model_matrix_ori, here("data/model_matrix_ori.rds"))
model_matrix_ori <- readRDS(here("data/model_matrix_ori.rds"))
```

```{r, fig.width=10, fig.height=10}
model <- model_matrix_ori$model
data_matrix <- model_matrix_ori$data_matrix

data_matrix %>% 
  group_by(stt, inc) %>% 
  summarise(
    pred_all = sum(pred * pop2008) / sum(pop2008), 
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1])
  ) %>% 
  ungroup() %>% 
  left_join(stt_dict, by = c("stt" = "stt")) %>% 
  #  mutate(
  #   state_name = state.names[stt],
  #   state_abb = stt.label[stt]
  # ) %>%
  filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(select(dat.stt, state, rep2008), by = c("state_abbr" = "state")) %>%
  mutate(state_name = fct_reorder(state_name, rep2008, .desc = TRUE)) %>% 
  ggplot(aes(group = 1)) +
  geom_line(aes(x = inc, y = pred_all, color = "grey")) + 
  geom_line(aes(x = inc, y = pred_white, color = "orange")) + 
  scale_x_discrete(labels = c("poor", "", "mid", "", "rich")) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) +
  scale_color_identity() +
  labs(x = "", y = "") +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "none"
  )
```

## Replicate figure 2

```{r}
data_matrix <- data_matrix %>%
  mutate(plot.grp = paste(stt, inc, sep = "_"))

D2 <- data_matrix %>%
  group_by(plot.grp) %>%
  summarize(
    vote2008 = sum(vote2008 * pop2008) / sum(pop2008),
    vote2004 = sum(vote2004 * pop2004) / sum(pop2004),
    stt = unique(stt),
    inc = unique(inc)
  )

D3 <- data_matrix %>%
  filter(eth == 1) %>%
  group_by(plot.grp) %>%
  summarize(
    vote2008 = sum(vote2008 * pop2008) / sum(pop2008),
    vote2004 = sum(vote2004 * pop2004) / sum(pop2004),
    stt = unique(stt),
    inc = unique(inc)
  )

stt.inc <- expand.grid(stt = sort(unique(D2$stt)), inc = sort(unique(D2$inc))) %>%
  mutate(
    fit1 = NA, se1 = NA, mu1 = NA,
    fit2 = NA, se2 = NA, mu2 = NA
  )

for (i in seq_len(nrow(stt.inc))) {
  # Filter based on stt and inc
  filter_cond <- dat.vot$stt == stt.inc$stt[i] & dat.vot$inc == stt.inc$inc[i] & dat.vot$year == 2008
  ok <- which(filter_cond)
  if (length(ok) > 1) {
    stt.inc$fit1[i] <- D2$vote2008[D2$stt == stt.inc$stt[i] & D2$inc == stt.inc$inc[i]]
    stt.inc$mu1[i] <- min(0.98, max(0.02, weighted.mean(dat.vot$rvote[ok], w = dat.vot$weight[ok])))
    stt.inc$se1[i] <- sqrt((stt.inc$fit1[i] * (1 - stt.inc$fit1[i])) / length(ok))
  }

  ok <- which(filter_cond & dat.vot$eth == 1)
  if (length(ok) > 1) {
    stt.inc$fit2[i] <- D3$vote2008[D3$stt == stt.inc$stt[i] & D3$inc == stt.inc$inc[i]]
    stt.inc$mu2[i] <- min(0.98, max(0.02, weighted.mean(dat.vot$rvote[ok], w = dat.vot$weight[ok])))
    stt.inc$se2[i] <- sqrt((stt.inc$fit2[i] * (1 - stt.inc$fit2[i])) / length(ok))
  }
}
```

```{r, fig.width=10, fig.height=10, warning=FALSE}
title <- "2008 election:  McCain share of the two-party vote in each income category\nwithin each state among all voters (gray) and just non-Hispanic whites (orange)"
caption <- "Dots are weighted averages from pooled June-Nov Pew surveys; error bars show +/- 1 s.e. bounds.\n Curves are estimated using multilevel models and have a s.e. of about 3% at each point.\n States are ordered in decreasing order of McCain vote (Alaska, Hawaii, and D.C. excluded)"


stt.inc %>%
  left_join(stt_dict, by = c("stt" = "stt")) %>% 
  filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(select(dat.stt, state, rep2008), by = c("state_abbr" = "state")) %>%
  mutate(state_name = fct_reorder(state_name, rep2008, .desc = TRUE)) %>%
  ggplot(aes(group = 1)) +
  geom_line(aes(x = inc, y = fit1, color = "grey")) +
  geom_line(aes(x = inc, y = fit2, color = "orange")) +
  geom_pointrange(aes(x = as.numeric(inc), y = mu1, ymin = mu1 - se1, ymax = mu1 + se1, color = "grey"), fatten = 0.001, linewidth = 0.3) +
  geom_pointrange(aes(x = as.numeric(inc) + 0.1, y = mu2, ymin = mu2 - se2, ymax = mu2 + se2, color = "orange"), fatten = 0.001, linewidth = 0.3) +
  geom_hline(aes(yintercept = 0.5), color = "grey80", size = 0.2) +
  scale_x_discrete(labels = c("poor", "", "mid", "", "rich")) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) +
  scale_colour_identity() +
  labs(title = title, x = "", y = "", caption = caption) +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "none"
  )

ggsave("../figures/2008_stan_fig2_replicate.jpg", width = 10, height = 10, dpi = 300)
```


```{r}
# data_matrix$plot.grp <- apply(data_matrix[, c("stt", "inc")], 1, paste, collapse = "_")
# D2 <- summarize(group_by(data_matrix, plot.grp), vote2008 = sum(vote2008 * pop2008) / sum(pop2008), vote2004 = sum(vote2004 * pop2004) / sum(pop2004), stt = unique(stt), inc = unique(inc))
# D3 <- summarize(group_by(data_matrix[data_matrix$eth == 1, ], plot.grp), vote2008 = sum(vote2008 * pop2008) / sum(pop2008), vote2004 = sum(vote2004 * pop2004) / sum(pop2004), stt = unique(stt), inc = unique(inc))
#
# # 2008
# stt.inc <- as.data.frame(expand.grid(sort(unique(D2$stt)), sort(unique(D2$inc))))
# colnames(stt.inc) <- c("stt", "inc")
# stt.inc$fit2 <- stt.inc$se2 <- stt.inc$mu2 <-
#   stt.inc$fit1 <- stt.inc$se1 <- stt.inc$mu1 <- NA
#
# for (i in 1:nrow(stt.inc)) {
#   ok <- which(dat.vot$stt == stt.inc$stt[i] & dat.vot$inc == stt.inc$inc[i] & dat.vot$year == 2008)
#   if (length(ok) > 1) {
#     stt.inc$fit1[i] <- D2$vote2008[D2$stt == stt.inc$stt[i] & D2$inc == stt.inc$inc[i]]
#     stt.inc$mu1[i] <- min(0.98, max(0.02, weighted_mean(dat.vot$rvote[ok], w = dat.vot$weight[ok])))
#     stt.inc$se1[i] <- sqrt((stt.inc$fit1[i] * (1 - stt.inc$fit1[i])) / length(ok))
#   }
#   ok <- which(dat.vot$stt == stt.inc$stt[i] & dat.vot$inc == stt.inc$inc[i] & dat.vot$year == 2008 & dat.vot$eth == 1)
#   if (length(ok) > 1) {
#     stt.inc$fit2[i] <- D3$vote2008[D3$stt == stt.inc$stt[i] & D3$inc == stt.inc$inc[i]]
#     stt.inc$mu2[i] <- min(0.98, max(0.02, weighted_mean(dat.vot$rvote[ok], w = dat.vot$weight[ok])))
#     stt.inc$se2[i] <- sqrt((stt.inc$fit2[i] * (1 - stt.inc$fit2[i])) / length(ok))
#   }
# }
#
# png("2008_stan_fig2.png", height = 10, width = 10, res = 300, units = "in")
# graph.dims <- c(7, 7)
# par(
#   mfrow = graph.dims, mar = c(1, 0.75, 1, 0.75), tck = 0, mgp = c(1.5, .5, 0),
#   oma = c(7, 2, 4, 0), lwd = 0.5
# )
# sort.state <- rev(order(dat.stt$rep2008[1:51]))
# state.names <- c(state.name[1:8], "Washington DC", state.name[9:50])
# colors <- c("gray40", "darkorange")
# pchs <- c(20, 21)
# count <- 0
# for (i in sort.state) {
#   if (!(stt.label[i] %in% c("AK", "HI", "DC"))) {
#     count <- count + 1
#     plot(c(1, 5), c(0, 1), xlab = "", ylab = "", xaxt = "n", yaxt = "n", type = "n", yaxs = "i")
#     if (count %% graph.dims[2] == 1) {
#       axis(2, c(.02, .5, .95), c("0%", "50%", "100%"), cex.axis = 1.1, lwd = 0.5)
#     }
#     if (count > (48 - graph.dims[2])) {
#       axis(1, c(1.2, 3, 4.8), c("poor", "mid", "rich"), cex.axis = 1.2, lwd = 0.5)
#     }
#     abline(.5, 0, col = "gray", lwd = .5)
#
#     tmp <- stt.inc[stt.inc$stt == i, ]
#     points(1:5 - 0.05, tmp$mu1, pch = 20, col = colors[1], cex = 0.5)
#     segments(1:5 - 0.05, tmp$mu1 - tmp$se1, 1:5 - 0.05, tmp$mu1 + tmp$se1, col = colors[1])
#     points(1:5, tmp$fit1, type = "l", col = colors[1])
#
#     points(1:5 + 0.05, tmp$mu2, ylim = c(0, 1), pch = 20, col = colors[2], cex = 0.5)
#     segments(1:5 + 0.05, tmp$mu2 - tmp$se2, 1:5 + 0.05, tmp$mu2 + tmp$se2, col = colors[2])
#     points(1:5, tmp$fit2, type = "l", col = colors[2])
#     text(3, .9, state.names[i], cex = 1.3)
#   }
# }
# mtext("2008 election:  McCain share of the two-party vote in each income category\nwithin each state among all voters (gray) and just non-Hispanic whites (orange)", outer = TRUE, cex = 1, side = 3, line = 1)
# mtext(" Dots are weighted averages from pooled June-Nov Pew surveys; error bars show +/- 1 s.e. bounds.\n Curves are estimated using multilevel models and have a s.e. of about 3% at each point.\n States are ordered in decreasing order of McCain vote (Alaska, Hawaii, and D.C. excluded).", outer = TRUE, cex = .9, side = 1, line = 5)
# dev.off()
```
