---
title: "Data exploration"
author: "Farhan Reynaldo"
date: "2024-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("scripts/data-modeling.Rmd")
```

```{r}
# Data wrangling
library(tidyverse)
library(arrow)
library(here)
library(haven)
library(janitor)
library(ipumsr)
library(arm)

# Bayesian
library(rstanarm)
library(tidybayes)
library(lme4)

# Maps
library(ggtext)
library(usmap)
library(sf)

source(here::here("src/election.R"))
source(here::here("src/helpers.R"))
source(here::here("src/theme.R"))
source(here::here("src/load_data.R"))

options(mc.cores = parallel::detectCores())

map_data <- usmap::us_map(regions = "states")
poststrat_data <- read.table(here("data/census-pums-pop-2000-04-08.dat"), 
                             sep = "\t", header = TRUE)
```

using zipcode to and see the population density.

```{r}
fit_model <- function(election_processed, states_data, iter = 500) {
  data_matrix <- expand.grid(
    stt = factor(1:length(stt.label)),
    eth = factor(1:length(eth.label)),
    inc = factor(1:length(inc.label)),
    age = factor(1:length(age.label))
  ) %>%
    mutate(
      grp = apply(., 1, paste, collapse = "_"),
      ix = row_number()
    ) %>%
    left_join(states_data, by = c("stt" = "stt")) %>%
    mutate(
      reg = factor(reg.lkup[as.numeric(stt)]),
      z_inc = arm::rescale(as.numeric(inc))
    )
  
  election_subset <- election_processed %>%
    mutate(
      # Vote for Republican
      vote = ifelse(vote == "Republican", 1, 0),
      grp = apply(.[, c("stt", "eth", "inc", "age")], 1, paste, collapse = "_"),
      ones = 1
    )

  # Calculate and add weighted results
  data_matrix <- calc_and_add_weighted_results(data_matrix, election_subset)

  # Build and fit model
  reg_formula <- as.formula(build_formula(level = 3))
  model <- stan_glmer(reg_formula, data = data_matrix, family = binomial(link = "logit"), iter = iter)
  
  pred <- posterior_epred(model, newdata = data_matrix)
  
  # Generate predictions
  list(model = model, data_matrix = data_matrix, pred = pred)
}
```

### Income-State 

```{r, fig.width=12, fig.height=12}
model_matrix_2020 <- readRDS(here("data/Model/model_matrix_2020.rds"))
model_matrix_2016 <- readRDS(here("data/Model/model_matrix_2016.rds"))
model_matrix_2012 <- readRDS(here("data/Model/model_matrix_2012.rds"))

poststrat_by_income_state <- function(model_matrix) {
  poststrat_data %>%
  mutate(grp = apply(.[, c("stt", "eth", "inc", "age")], 1, paste, collapse = "_")) %>%
  group_by(grp) %>%
  summarise(
    pop2004 = sum(wtd2004, na.rm = TRUE),
    pop2008 = sum(wtd2008, na.rm = TRUE)
  ) %>%
  right_join(model_matrix$data_matrix, by = "grp") %>%
  arrange(ix) %>% 
  mutate(pred = colMeans(model_matrix$pred)) %>%
  group_by(year, stt, inc) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1]),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
    se_white = sqrt((pred_white * (1 - pred_white)) / sum(n[eth == 1]))
  ) %>% 
  ungroup()
}

# Loop over model matrix and combine df using purrr
model_matrices <- list(model_matrix_2020, model_matrix_2016, model_matrix_2012)
poststrat_by_income_state <- map(model_matrices, poststrat_by_income_state)

poststrat_by_income_state %>% 
  list_rbind() %>% 
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  mutate(year = as.factor(year)) %>%
  ggplot(aes(group = year, color = year)) + 
  geom_line(aes(x = inc, y = pred_all), linewidth = 1, alpha = 0.8) + 
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  facet_wrap(~state_name, ncol = 7) + 
  scale_x_discrete(labels = c("poor", "", "mid", "", "rich")) +
  scale_color_manual(values = c("#FBCCA7", "#F9B27C", "#F79950")) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) + 
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "", y = "", 
       title = "Republican vote share for each income category across states-year") + 
  theme_classic() +
  theme(
    plot.title = element_text(size = 16, hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "top"
  )
```


### 2020

```{r}
year <- 2020
# Process states data
states_data <- process_states_data(states_election_data, states_pop_income_data, year)
# Process election data
election_processed <- process_election_data(election_all, year)
# Process IPUMS data for poststratification
# poststrat_data <- process_ipums_data(ipums_data, year)
election_subset_2020 <- election_processed %>%
    mutate(
      # Vote for Republican
      vote = ifelse(vote == "Republican", 1, 0),
    ) %>% 
  group_by(stt, inc) %>% 
  summarise(mu_all = min(0.98, max(0.02, weighted.mean(vote, weight))),
            mu_white = min(0.98, max(0.02, weighted.mean(vote[eth==1], weight[eth==1])))) %>% 
  ungroup()

# model_matrix_2020 <- fit_model(election_processed, states_data, iter = 2000)
# saveRDS(model_matrix_2020, here("data/model_matrix_2020.rds"))
```

```{r, fig.width=12, fig.height=12}
model_matrix_2020 <- readRDS(here("data/model_matrix_2020.rds"))

model <- model_matrix_2020$model
data_matrix <- model_matrix_2020$data_matrix

# Poststratification
result <- poststrat_data %>%
  mutate(grp = apply(.[, c("stt", "eth", "inc", "age")], 1, paste, collapse = "_")) %>%
  group_by(grp) %>%
  summarise(
    pop2004 = sum(wtd2004, na.rm = TRUE),
    pop2008 = sum(wtd2008, na.rm = TRUE)
  ) %>%
  right_join(data_matrix, by = "grp") %>%
  arrange(ix)

title <- "2020 Election: Republican vote share for each income category across states\namong all voters (grey) and white voters (orange)"

# Plot results
plot_result <- result %>%
  mutate(pred = colMeans(model_matrix_2020$pred)) %>%
  group_by(stt, inc) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1]),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
    se_white = sqrt((pred_white * (1 - pred_white)) / sum(n[eth == 1]))
  ) %>% 
  ungroup() %>%
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(states_data %>% filter(year == year) %>% select(state_abbr, rep_votes), by = c("state_abbr" = "state_abbr")) %>%
  mutate(state_name = fct_reorder(state_name, rep_votes, .desc = TRUE)) %>% 
  arrange(-rep_votes) %>% 
  left_join(election_subset_2020, by = c("stt", "inc"))

plot_result %>% 
  ggplot(aes(group = 1)) +
  geom_line(aes(x = inc, y = pred_all, color = "grey")) +
  geom_line(aes(x = inc, y = pred_white, color = "orange")) +
  # geom_point(aes(x = inc, y = mu_all, color = "grey"), size = 2) +
  # geom_point(aes(x = inc, y = mu_white, color = "orange"), size = 2) +
  geom_pointrange(aes(x = as.numeric(inc), y = mu_all, ymin = mu_all - se_all, ymax = mu_all + se_all, color = "grey"), fatten = 0.001, linewidth = 0.3) +
  geom_pointrange(aes(x = as.numeric(inc) + 0.1, y = mu_white, ymin = mu_white - se_white, ymax = mu_white + se_white, color = "orange"), fatten = 0.001, linewidth = 0.3) +
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  scale_x_discrete(labels = c("poor", "", "mid", "", "rich")) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) +
  scale_color_identity() +
  labs(title = title, x = "", y = "") +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "none"
  )

ggsave(here("figures/2020_election.jpg"), width = 10, height = 10, dpi = 300)
```

```{r}
map_data %>%
  left_join(plot_result, by = c("abbr" = "state_abbr")) %>%
  drop_na(inc, abbr) %>%
  left_join(data.frame(inc = factor(1:5), income_group = inc.label)) %>% 
  ggplot() +
  geom_sf(aes(fill = pred_white)) +
  facet_wrap(~income_group) +
  coord_sf() +
  scale_fill_gradient2(
    low = "#2c7fb8", mid = "#f7f7f7", high = "#d73027", 
    midpoint = 0.5, labels = scales::percent_format()
  ) +
  theme_maps() +
  theme(strip.text.x = element_text(size = 14)) +
  labs(title = "2020 election: Estimated Republican vote share across income by state")
```

```{r}
map_data %>% 
  left_join(result %>%
  mutate(pred = colMeans(model_matrix_2020$pred)) %>%
  group_by(stt, age) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1]),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
    se_white = sqrt((pred_white * (1 - pred_white)) / sum(n[eth == 1]))
  ) %>% 
  ungroup() %>% 
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  filter(!state_abbr %in% c("AK", "HI", "DC")), by = c("abbr" = "state_abbr")) %>% 
  left_join(data.frame(age = factor(1:4), age_group = age.label)) %>% 
  drop_na(age, abbr) %>% 
  ggplot() + 
  geom_sf(aes(fill = pred_all)) +
  facet_wrap(~age_group) +
  coord_sf() +
  scale_fill_gradient2(
    low = "#2c7fb8", mid = "#f7f7f7", high = "#d73027",
    midpoint = 0.5, labels = scales::percent_format()
  ) +
  theme_maps() +
  theme(strip.text.x = element_text(size = 14)) +
  labs(title = "2020 election: Estimated Republican vote share across age group by state")
```

```{r}
map_data %>% 
  left_join(result %>%
  mutate(pred = colMeans(model_matrix_2020$pred)) %>%
  group_by(stt, eth) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
  ) %>% 
  ungroup() %>% 
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  filter(!state_abbr %in% c("AK", "HI", "DC")), by = c("abbr" = "state_abbr")) %>% 
  left_join(data.frame(eth = factor(1:length(eth.label)), eth_group = eth.label)) %>% 
  drop_na(eth, abbr) %>% 
  ggplot() + 
  geom_sf(aes(fill = pred_all)) +
  facet_wrap(~eth_group) +
  coord_sf() +
  scale_fill_gradient2(
    low = "#2c7fb8", mid = "#f7f7f7", high = "#d73027",
    midpoint = 0.5, labels = scales::percent_format()
  ) +
  theme_maps() +
  theme(strip.text.x = element_text(size = 14)) +
  labs(title = "2020 election: Estimated Republican vote share across age group by state")
```

### 2016

```{r}
year <- 2016
# Process states data
states_data <- process_states_data(states_election_data, states_pop_income_data, year)
# Process election data
election_processed <- process_election_data(election_all, year)
# Process IPUMS data for poststratification
# poststrat_data <- process_ipums_data(ipums_data, year)
election_subset_2016 <- election_processed %>%
    mutate(
      # Vote for Republican
      vote = ifelse(vote == "Republican", 1, 0),
    ) %>% 
  group_by(stt, inc) %>% 
  summarise(mu_all = min(0.98, max(0.02, weighted.mean(vote, weight))),
            mu_white = min(0.98, max(0.02, weighted.mean(vote[eth==1], weight[eth==1])))) %>% 
  ungroup()

# model_matrix_2016 <- fit_model(election_processed, states_data, iter = 2000)
# saveRDS(model_matrix_2016, here("data/model_matrix_2016.rds"))
```

```{r, fig.width=12, fig.height=12}
# Plot results
model_matrix_2016 <- readRDS(here("data/model_matrix_2016.rds"))
model <- model_matrix_2016$model
data_matrix <- model_matrix_2016$data_matrix

# Poststratification
result <- poststrat_data %>%
  mutate(grp = apply(.[, c("stt", "eth", "inc", "age")], 1, paste, collapse = "_")) %>%
  group_by(grp) %>%
  summarise(
    pop2004 = sum(wtd2004, na.rm = TRUE),
    pop2008 = sum(wtd2008, na.rm = TRUE)
  ) %>%
  right_join(data_matrix, by = "grp") %>%
  arrange(ix)

title <- "2016 Election: Republican vote share for each income category across states\namong all voters (grey) and white voters (orange)"

plot_result <- result %>%
  mutate(pred = colMeans(model_matrix_2016$pred)) %>%
  group_by(stt, inc) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1]),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
    se_white = sqrt((pred_white * (1 - pred_white)) / sum(n[eth == 1]))
  ) %>%
  ungroup() %>%
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(states_data %>% filter(year == year) %>% select(state_abbr, rep_votes), by = c("state_abbr" = "state_abbr")) %>%
  mutate(state_name = fct_reorder(state_name, rep_votes, .desc = TRUE)) %>% 
  arrange(-rep_votes) %>% 
  left_join(election_subset_2016, by = c("stt", "inc"))
  
plot_result %>% 
  ggplot(aes(group = 1)) +
  geom_line(aes(x = inc, y = pred_all, color = "grey")) +
  geom_line(aes(x = inc, y = pred_white, color = "orange")) +
  # geom_point(aes(x = inc, y = mu_all, color = "grey"), size = 2) +
  # geom_point(aes(x = inc, y = mu_white, color = "orange"), size = 2) +
  geom_pointrange(aes(x = as.numeric(inc), y = mu_all, ymin = mu_all - se_all, ymax = mu_all + se_all, color = "grey"), fatten = 0.001, linewidth = 0.3) +
  geom_pointrange(aes(x = as.numeric(inc) + 0.1, y = mu_white, ymin = mu_white - se_white, ymax = mu_white + se_white, color = "orange"), fatten = 0.001, linewidth = 0.3) +
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  scale_x_discrete(labels = c("poor", "", "mid", "", "rich")) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) +
  scale_color_identity() +
  labs(title = title, x = "", y = "") +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "none"
  )

ggsave(here("figures/2016_election.jpg"), width = 10, height = 10, dpi = 300)
```

### 2012

```{r}
year <- 2012
# Process states data
states_data <- process_states_data(states_election_data, states_pop_income_data, year)
# Process election data
election_processed <- process_election_data(election_all, year)
# Process IPUMS data for poststratification
# poststrat_data <- process_ipums_data(ipums_data, year)
election_subset_2012 <- election_processed %>%
    mutate(
      # Vote for Republican
      vote = ifelse(vote == "Republican", 1, 0),
    ) %>% 
  group_by(stt, inc) %>% 
  summarise(mu_all = min(0.98, max(0.02, weighted.mean(vote, weight))),
            mu_white = min(0.98, max(0.02, weighted.mean(vote[eth==1], weight[eth==1])))) %>% 
  ungroup()

# model_matrix_2012 <- fit_model(election_processed, states_data, iter = 2000)
# saveRDS(model_matrix_2012, here("data/model_matrix_2012.rds"))
```

```{r, fig.width=12, fig.height=12}
model_matrix_2012 <- readRDS(here("data/model_matrix_2012.rds"))
model <- model_matrix_2012$model
data_matrix <- model_matrix_2012$data_matrix

# Poststratification
result <- poststrat_data %>%
  mutate(grp = apply(.[, c("stt", "eth", "inc", "age")], 1, paste, collapse = "_")) %>%
  group_by(grp) %>%
  summarise(
    pop2004 = sum(wtd2004, na.rm = TRUE),
    pop2008 = sum(wtd2008, na.rm = TRUE)
  ) %>%
  right_join(data_matrix, by = "grp") %>%
  arrange(ix)

title <- "2012 Election: Republican vote share for each income category across states\namong all voters (grey) and white voters (orange)"

# Plot results
plot_result <- result %>%
  mutate(pred = colMeans(model_matrix_2012$pred)) %>%
  group_by(stt, inc) %>%
  summarise(
    pred_all = sum(pred * pop2008, na.rm = TRUE) / sum(pop2008, na.rm = TRUE),
    pred_white = sum(pred[eth == 1] * pop2008[eth == 1]) / sum(pop2008[eth == 1]),
    se_all = sqrt((pred_all * (1 - pred_all)) / sum(n)),
    se_white = sqrt((pred_white * (1 - pred_white)) / sum(n[eth == 1]))
  ) %>%
  ungroup() %>%
  left_join(stt_dict, by = c("stt" = "stt")) %>%
  filter(!state_abbr %in% c("AK", "HI", "DC")) %>%
  left_join(states_data %>% filter(year == year) %>% select(state_abbr, rep_votes), by = c("state_abbr" = "state_abbr")) %>%
  mutate(state_name = fct_reorder(state_name, rep_votes, .desc = TRUE)) %>% 
  arrange(-rep_votes) %>% 
  left_join(election_subset_2016, by = c("stt", "inc"))
  
plot_result %>% 
  ggplot(aes(group = 1)) +
  geom_line(aes(x = inc, y = pred_all, color = "grey")) +
  geom_line(aes(x = inc, y = pred_white, color = "orange")) +
  # geom_point(aes(x = inc, y = mu_all, color = "grey"), size = 2) +
  # geom_point(aes(x = inc, y = mu_white, color = "orange"), size = 2) +
  geom_pointrange(aes(x = as.numeric(inc), y = mu_all, ymin = mu_all - se_all, ymax = mu_all + se_all, color = "grey"), fatten = 0.001, linewidth = 0.3) +
  geom_pointrange(aes(x = as.numeric(inc) + 0.1, y = mu_white, ymin = mu_white - se_white, ymax = mu_white + se_white, color = "orange"), fatten = 0.001, linewidth = 0.3) +
  geom_hline(aes(yintercept = 0.5), color = "grey80", linewidth = 0.2) +
  scale_x_discrete(labels = c("poor", "", "mid", "", "rich")) +
  scale_y_continuous(labels = scales::label_percent(), breaks = seq(0, 1, 0.5)) +
  scale_color_identity() +
  labs(title = title, x = "", y = "") +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~state_name, ncol = 7) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, margin = margin(0, 0, 20, 0)),
    plot.caption = element_text(hjust = 0.5, margin = margin(10, 0, 0, 0)),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 10),
    legend.position = "none"
  )

ggsave(here("figures/2012_election.jpg"), width = 10, height = 10, dpi = 300)
```

### Check if value similar

```{r}
year <- 2016
election_processed <- process_election_data(election_all, year)
data_matrix <- expand.grid(
    stt = factor(1:length(stt.label)),
    inc = factor(1:length(inc.label))
  ) %>%
    mutate(
      grp = apply(., 1, paste, collapse = "_"),
      ix = row_number()
    ) %>%
    left_join(states_data, by = c("stt" = "stt")) %>%
    mutate(
      reg = factor(reg.lkup[as.numeric(stt)]),
      z_inc = arm::rescale(as.numeric(inc))
    )
  
election_subset <- election_processed %>%
  mutate(
    # Vote for Republican
    vote = ifelse(vote == "Republican", 1, 0),
    grp = apply(.[, c("stt", "inc")], 1, paste, collapse = "_"),
    ones = 1
  ) %>% 
  group_by(grp) %>%
  summarise(
    vote = sum(vote),
    total = n()
  )

data_mat <- data_matrix %>% 
  left_join(election_subset, by = c("grp")) 

dat.vot <- read.table(here("data/votechoice2000-04-08.dat"), header=T, sep="\t")
dat.vot$weight[is.na(dat.vot$weight)] <- 1
ok <- apply(is.na(dat.vot[1:8]), 1, sum)==0 & 
      (dat.vot$cit==1 | is.na(dat.vot$cit)) & 
      (dat.vot$regist=="registered" | is.na(dat.vot$regist))
dat.vot <- dat.vot[ok,]
dat.vot$reg <- reg.lkup[dat.vot$stt]
dat.vot$year <- car::recode(dat.vot$file, "'2000-ann'=2000; '2004-ann'=2004; '2008-pew'=2008")
dat.vot <- dat.vot[dat.vot$year != 2000,]

M2 <- stan_glmer(rvote ~ inc + (1 + inc | stt), weights=weight, data=dat.vot, 
            subset=dat.vot$file=="2008-pew" & dat.vot$eth==1, iter = 500,
             family=binomial, verbose = T)
 
stt.inc.df <- expand.grid(stt=1:51, inc=1:5)

pred <- colMeans(posterior_epred(M2, stt.inc.df))

stt.inc.df %>% 
  mutate(
    across(everything(), as.factor),
    pred = pred) %>% 
  left_join(stt_dict, by = c("stt" = "stt")) %>% 
  ggplot(aes(x = inc, y = pred, color = state_name, group = state_name)) +
  geom_line(data = . %>% filter(!state_abbr %in% c("MS", "UT", "CT")), color = "grey80", linewidth = 0.8) + 
  geom_line(data = . %>% filter(state_abbr %in% c("MS", "UT", "CT")), color = "orange", linewidth = 0.8) +
  geom_text(data = . %>% filter(state_abbr %in% c("MS", "UT", "CT"), inc == max(as.numeric(inc))), aes(label = state_abbr), color = "orange", hjust = 0, nudge_x = 0.1) +
  theme_classic()
```


```{r}
if (!file.exists("fit_2012.rds")) {
  election_2012_grouped <- election_2012 %>%
    group_by(state, income_group, age_group, race, educ_group) %>%
    summarise(vote_rep = sum(vote_rep), vote_total = n()) %>%
    ungroup()

  fit_2012 <- stan_glmer(
    cbind(vote_rep, vote_total - vote_rep) ~ (1 | state) +
      (1 | income_group) + (1 | age_group) + (1 | race) +
      (1 | educ_group),
    data = election_2012_grouped, family = binomial("logit")
  )
} else {
  fit_2012 <- readRDS("fit_2012.rds")
}

# posterior_prob <- posterior_epred(fit_2012, newdata = poststrat_2012)
# poststrat_prob <- posterior_prob %*% poststrat_2012$n / sum(poststrat_2012$n)
# c(mean = mean(poststrat_prob), sd = sd(poststrat_prob))
```

```{r}
income_prop <- poststrat_2012 %>%
  group_by(income_group) %>%
  mutate(prop = n / sum(n)) %>%
  ungroup()
```

```{r, fig.width=12, fig.height=8}
income_state_prop <- poststrat_2012 %>%
  group_by(income_group, state) %>%
  mutate(prop = n / sum(n)) %>%
  ungroup()

res_income_state <- income_state_prop %>%
  add_epred_draws(fit_2012) %>%
  mutate(pred_prop = .epred * prop) %>%
  group_by(income_group, state, .draw) %>%
  summarise(pred = sum(pred_prop)) %>%
  group_by(income_group, state) %>%
  summarise(
    mean = mean(pred),
    lower = quantile(pred, 0.025),
    upper = quantile(pred, 0.975)
  ) %>%
  ungroup()

map_data %>%
  left_join(res_income_state, by = c("full" = "state")) %>%
  ggplot() +
  geom_sf(aes(fill = mean)) +
  facet_wrap(~income_group) +
  coord_sf() +
  scale_fill_gradient2(
    low = "#2c7fb8", mid = "#f7f7f7", high = "#d73027",
    midpoint = 0.5, labels = scales::percent_format()
  ) +
  theme_maps() +
  theme(strip.text.x = element_text(size = 14)) +
  labs(title = "Estimated Republican vote share across income by state")
```

```{r}
election_all %>% 
  mutate(diff = weight - weight_cumulative) %>% 
  ggplot(aes(diff)) +
  geom_histogram()
```

